/**
 * Partner application location data (W5f): country choices and city
 * suggestions for the staged application form.
 *
 * Pure static data with no server-only imports, so the client-side wizard
 * (components/partners/ApplyWizard.tsx) can import it directly. The country
 * select is rendered as a native <select> with <optgroup>s: the main source
 * markets first, then the complete alphabetical list. The city field stays a
 * free-text input — suggestions only feed a <datalist>, so any value remains
 * valid (the API contract does not change).
 *
 * Names are common English short names ("Russia", not "Russian Federation");
 * diacritics are avoided ("Curacao", "Dusseldorf") so the alphabetical order
 * is unambiguous under a plain "en" collator.
 */

/** The main source markets, offered first in the country select. */
export const MAIN_MARKETS = [
  "Armenia",
  "Georgia",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Iran",
  "Iraq",
  "Jordan",
  "Lebanon",
  "Egypt",
  "Turkey",
  "Russia",
  "Kazakhstan",
  "Uzbekistan",
  "Azerbaijan",
  "India",
  "Pakistan",
  "United Kingdom",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "United States",
  "Canada",
  "China",
] as const;

/**
 * Sovereign countries plus the main territories. Kept unsorted in source for
 * readability and sorted once at module load; the exported value is always
 * alphabetical.
 */
const ALL_COUNTRIES_RAW = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curacao",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of the Congo",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "U.S. Virgin Islands",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

const countryCollator = new Intl.Collator("en", { sensitivity: "base" });

/** Compares two country names in alphabetical ("en") order. */
export function compareCountryNames(a: string, b: string): number {
  return countryCollator.compare(a, b);
}

/** The complete list of countries and main territories, sorted alphabetically. */
export const ALL_COUNTRIES: readonly string[] = [...ALL_COUNTRIES_RAW].sort(
  compareCountryNames,
);

export interface CountryGroup {
  label: string;
  countries: readonly string[];
}

/**
 * Country choices for the application form select: the main source markets
 * first, then the full alphabetical list. The main markets also appear in the
 * full list below, which is intentional — the "Main markets" optgroup is a
 * shortcut, not a separate set.
 */
export const COUNTRIES: readonly CountryGroup[] = [
  { label: "Main markets", countries: MAIN_MARKETS },
  { label: "All countries", countries: ALL_COUNTRIES },
];

/**
 * City suggestions for the main markets only (6–12 each). These feed a
 * <datalist>; the city input always allows free typing.
 */
export const CITY_SUGGESTIONS: Readonly<Record<string, readonly string[]>> = {
  Armenia: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan", "Abovyan", "Kapan", "Armavir"],
  Georgia: ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Gori", "Zugdidi", "Poti", "Telavi"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain", "Al Ain"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Dhahran", "Taif", "Tabuk", "Abha"],
  Qatar: ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Lusail", "Umm Salal", "Al Daayen", "Mesaieed"],
  Kuwait: ["Kuwait City", "Hawally", "Salmiya", "Farwaniya", "Ahmadi", "Jahra", "Fahaheel", "Mangaf"],
  Bahrain: ["Manama", "Muharraq", "Riffa", "Hamad Town", "Isa Town", "Budaiya", "Jidhafs", "Sitra"],
  Oman: ["Muscat", "Salalah", "Sohar", "Nizwa", "Sur", "Seeb", "Ibri", "Barka"],
  Iran: ["Tehran", "Mashhad", "Isfahan", "Shiraz", "Tabriz", "Qom", "Ahvaz", "Karaj", "Kerman", "Yazd"],
  Iraq: ["Baghdad", "Basra", "Erbil", "Mosul", "Najaf", "Karbala", "Sulaymaniyah", "Kirkuk"],
  Jordan: ["Amman", "Zarqa", "Irbid", "Aqaba", "Madaba", "Salt", "Jerash", "Karak"],
  Lebanon: ["Beirut", "Tripoli", "Sidon", "Tyre", "Byblos", "Zahle", "Baalbek", "Jounieh"],
  Egypt: ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan", "Sharm El Sheikh", "Hurghada", "Port Said", "Suez", "Mansoura"],
  Turkey: ["Istanbul", "Ankara", "Izmir", "Antalya", "Bursa", "Adana", "Gaziantep", "Konya", "Trabzon", "Bodrum"],
  Russia: ["Moscow", "Saint Petersburg", "Kazan", "Novosibirsk", "Yekaterinburg", "Sochi", "Nizhny Novgorod", "Samara", "Krasnodar", "Vladivostok"],
  Kazakhstan: ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe", "Atyrau", "Aktau", "Taraz"],
  Uzbekistan: ["Tashkent", "Samarkand", "Bukhara", "Khiva", "Fergana", "Nukus", "Andijan", "Namangan"],
  Azerbaijan: ["Baku", "Ganja", "Sumqayit", "Gabala", "Sheki", "Lankaran", "Nakhchivan", "Quba"],
  India: ["Mumbai", "Delhi", "Bengaluru", "Chennai", "Hyderabad", "Kolkata", "Jaipur", "Kochi", "Goa", "Pune"],
  Pakistan: ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad", "Multan", "Peshawar", "Quetta"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Edinburgh", "Glasgow", "Liverpool", "Bristol", "Leeds"],
  Germany: ["Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne", "Stuttgart", "Dusseldorf", "Leipzig", "Dresden"],
  France: ["Paris", "Lyon", "Marseille", "Nice", "Toulouse", "Bordeaux", "Strasbourg", "Lille"],
  Italy: ["Rome", "Milan", "Venice", "Florence", "Naples", "Turin", "Bologna", "Verona"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville", "Malaga", "Bilbao", "Alicante", "Palma de Mallorca"],
  "United States": ["New York", "Los Angeles", "Miami", "Chicago", "Houston", "San Francisco", "Las Vegas", "Boston", "Washington DC", "Orlando"],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Edmonton", "Quebec City", "Winnipeg"],
  China: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Xi'an", "Hangzhou", "Chongqing"],
};

/** City suggestions for a country, or an empty list when there are none. */
export function getCitySuggestions(country: string): readonly string[] {
  return CITY_SUGGESTIONS[country] ?? [];
}
